[phases.setup]
nixPkgs = ['python312', 'postgresql']

[phases.install]
cmds = [
  'python3 -m venv /opt/venv',
  '/opt/venv/bin/pip install --upgrade pip setuptools wheel',
  '/opt/venv/bin/pip install -r requirements.txt'
]

[phases.build]
cmds = ['cd apps/backend && /opt/venv/bin/python manage.py collectstatic --noinput']

[start]
cmd = 'bash /app/start.sh'
