[phases.setup]
nixPkgs = ['python312', 'postgresql']

[phases.install]
cmds = [
  'cd ouvy_saas',
  'python3 -m ensurepip --upgrade',
  'python3 -m pip install --upgrade pip setuptools wheel',
  'python3 -m pip install -r requirements.txt'
]

[phases.build]
cmds = ['cd ouvy_saas && python3 manage.py collectstatic --noinput']

[start]
cmd = 'cd ouvy_saas && python3 manage.py migrate --noinput && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 3 --timeout 120'
